Update r.yml
adding debugging

diff --git a/.github/workflows/r.yml b/.github/workflows/r.yml
--- a/.github/workflows/r.yml
+++ b/.github/workflows/r.yml
@@ -51,6 +51,14 @@ jobs:
         sudo apt-get update -y || true
         sudo apt-get install -y pandoc
 
+    - name: Debug Installed Tools
+      run: |
+       echo "R version:"
+       Rscript -e "R.version"
+       echo "Checking pkg-config installation:"
+       which pkg-config || echo 'pkg-config not found'
+       pkg-config --version || echo 'pkg-config version issue'
+
     - name: Install system dependencies (macOS)
       if: matrix.config.os == 'macOS-latest'
       run: |
